language: cpp

compiler:
  - gcc

branches:
  only:
    - travis

before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake libboost-all-dev libqt4-dev qt4-dev-tools libvtk5-qt4-dev libinsighttoolkit-dev

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=Release -DSUPERBUILD:BOOL=OFF ..
  - make -j4
