set( GOFIGURE2_INCLUDE_DIRS_SOURCE_TREE
  ${GOFIGURE2_SOURCE_DIR}
  ${GOFIGURE2_SOURCE_DIR}/Code/
  ${GOFIGURE2_SOURCE_DIR}/Code/IO/
  ${GOFIGURE2_SOURCE_DIR}/Code/GUI/lib/
  ${GOFIGURE2_SOURCE_DIR}/Code/Filters/
  ${GOFIGURE2_SOURCE_DIR}/Main/
)

set( GOFIGURE2_INCLUDE_DIRS_MEGAVTK_SOURCE_TREE
  ${MEGAVTK2_SOURCE_DIR}/vtkItk
  ${MEGAVTK2_SOURCE_DIR}/vtkRenderingAddOn
  ${MEGAVTK2_SOURCE_DIR}
)

set( GOFIGURE2_INCLUDE_DIRS_EXTERNAL_SOURCE_TREE
  ${GOFIGURE2_EXTERNAL_SOURCE_DIR}
  ${GOFIGURE2_EXTERNAL_SOURCE_DIR}/vtkLSM
  ${GOFIGURE2_EXTERNAL_SOURCE_DIR}/itkQt
  ${GOFIGURE2_EXTERNAL_SOURCE_DIR}/PoissonReconstruction
)

set( GOFIGURE2_INCLUDE_DIRS_BINARY_TRE
  ${GOFIGURE2_BINARY_DIR}
  ${GOFIGURE2_BINARY_DIR}/Code/
  ${GOFIGURE2_BINARY_DIR}/Code/IO/
  ${GOFIGURE2_BINARY_DIR}/Code/GUI/lib/
  ${GOFIGURE2_BINARY_DIR}/Code/Filters/
  ${GOFIGURE2_BINARY_DIR}/Main/
)

set( GOFIGURE2_INCLUDE_DIRS_MEGAVTK_BINARY_TREE
  ${MEGAVTK2_BINARY_DIR}/vtkItk
  ${MEGAVTK2_BINARY_DIR}/vtkRenderingAddOn
  ${MEGAVTK2_BINARY_DIR}
)

set( GOFIGURE2_INCLUDE_DIRS_EXTERNAL_BINARY_TREE
  ${GOFIGURE2_EXTERNAL_BINARY_DIR}
  ${GOFIGURE2_EXTERNAL_BINARY_DIR}/vtkLSM
  ${GOFIGURE2_EXTERNAL_BINARY_DIR}/itkQt
  ${GOFIGURE2_EXTERNAL_BINARY_DIR}/PoissonReconstruction
)

set( GOFIGURE2_INCLUDE_DIRS
  ${GOFIGURE2_INCLUDE_DIRS_SOURCE_TREE}
  ${GOFIGURE2_INCLUDE_DIRS_MEGAVTK_SOURCE_TREE}
  ${GOFIGURE2_INCLUDE_DIRS_EXTERNAL_SOURCE_TREE}
  ${GOFIGURE2_INCLUDE_DIRS_BINARY_TREE}
  ${GOFIGURE2_INCLUDE_DIRS_MEGAVTK_BINARY_TREE}
  ${GOFIGURE2_INCLUDE_DIRS_EXTERNAL_BINARY_TREE}
)
