SET( VIDEO_SUPPORT)

#-----------------------------------------------------------------------------
# Is FFMPEG AVAILABLE ( FOR UNIX) MAC??
FIND_PACKAGE( FFMPEG )

IF( FFMPEG_FOUND )
  LIST( APPEND VIDEO_SUPPORT
    -DVTK_USE_FFMPEGi_ENCODER:BOOL=ON    
  )
ELSE( FFMPEG_FOUND)
  LIST( APPEND VIDEO_SUPPORT
    -DVTK_USE_FFMPEG_ENCODER:BOOL=OFF    
  )
ENDIF( FFMPEG_FOUND )

# DO STH FOR WINDOWS
# turn on video by default
IF( WIN32 )
  LIST(APPEND VIDEO_SUPPORT
    -DVTK_USE_AVI_ENCODER:BOOL=ON
  )
ENDIF( WIN32 )
