SET( VIDEO_SUPPORT )

#-----------------------------------------------------------------------------
# Is FFMPEG AVAILABLE ( FOR UNIX) MAC??
IF( NOT WIN32 )

  FIND_PACKAGE( FFMPEG )

  IF( FFMPEG_FOUND )
    LIST( APPEND VIDEO_SUPPORT
      -DVTK_USE_FFMPEG_ENCODER:BOOL=ON    
    )
  ELSE( FFMPEG_FOUND )
    LIST( APPEND VIDEO_SUPPORT
      -DVTK_USE_FFMPEG_ENCODER:BOOL=OFF    
    )
  ENDIF( FFMPEG_FOUND )

# DO STH FOR WINDOWS
# turn on video by default
ELSE( NOT WIN32 )
  LIST( APPEND VIDEO_SUPPORT
    -DVTK_USE_AVI_ENCODER:BOOL=ON
  )
ENDIF( NOT WIN32 )
