FIND_PACKAGE( Boost REQUIRED )

IF( Boost_FOUND )
  INCLUDE_DIRECTORIES( BEFORE ${Boost_INCLUDE_DIRS} )
ELSE( Boost_FOUND )
  MESSAGE( SEND_ERROR "BOOST NOT FOUND, CMAKE WILL STOP NOW")  
ENDIF( Boost_FOUND )
