# - Find SIKULI 

FIND_PATH( SIKULI_EXECUTABLE NAMES sikuli-ide.sh
  PATHS
  "$ENV{ProgramFiles}/Sikuli-IDE/"
  "$ENV{SystemDrive}/Sikuli-IDE/"
  PATH_SUFFIXES "bin"
  DOC "Specify the path to sikuli"
)
MARK_AS_ADVANCED( SIKULI_EXECUTABLE )

SET( SIKULI_COMMAND "${SIKULI_EXECUTABLE -t " )

IF( SIKULI_EXECUTABLE )
  SET( SIKULI_FOUND TRUE )
ELSE( SIKULI_EXECUTABLE )
  SET( SIKULI_FOUND FALSE )
ENDIF( SIKULI_EXECUTABLE )
