#ifndef QGOCOMPARER_H
#define QGOCOMPARER_H
/*
#include "itkImageToVTKImageFilter.h"
#include "itkSmartPointer.h"
#include "itkImage.h"
*/

#include "SnapshotHelper.h"
#include "vtkSmartPointer.h"
#include "ui_QGoComparer.h"
class vtkCamera;
class vtkImageData;
class vtkEventQtSlotConnect;
class QGoImageView;
class QGoCompareOrchestra;


class QGoComparer : public QWidget, protected Ui::QGoComparer {
    Q_OBJECT
public:
    QGoComparer(QString iComparerName, QWidget *parent = 0);

    ~QGoComparer();

    /** Set image displayed by the comparer
    */
    virtual void SetImage(vtkImageData* iImage);



    // returns the type of comparer (2 for 2D, 3 for 3D)
    virtual int GetComparerType()=0;

    /** get comparer's name
    */
    QString* GetName();

    /**Update the viewer contained in the widget
    */
    virtual void Update();

    /** render the viewer contained in the widget if any
    */
    virtual void Render();

    // get the camera of the current viewer;
    virtual vtkCamera* GetCamera();

    /* print the comparer information :
    *  it consists in the image information if any.
    */
    virtual void PrintOs(ostream &os) = 0;

    /** true if the widget has a viewer
    */
    bool HasViewer();

    /** Set the address of the current orchestra
    */
    void SetCurrentOrchestra(QGoCompareOrchestra* iCurrentOrchestra);

public slots:

    virtual QString SnapshotViewXY( const GoFigure::FileType& iType,
    const QString& iBaseName = tr( "Snapshot" ) ) = 0;


protected:
    void changeEvent(QEvent *e);

  QString                           m_currentComparerName;
  vtkImageData*                     m_currentImage;
  QString                           m_currentImageName;
  QGoImageView*                     m_currentView;
  QGoCompareOrchestra*              m_currentOrchestra;
  vtkEventQtSlotConnect*            m_VTKEventQtConnector;
private slots:

  // the QMetaObject::connectSlotsByName(QGoComparer)
  // is provided in the Setupui generated by moc




private:


  // delete the viewer contained in the widget
  void deleteViewer();
  // create the viewer contained in the widget
  virtual void createViewer() = 0;




};

#endif // QGOCOMPARER_H
