#!/bin/bash
# This script is to be used carefully!!! 
# If you don't know what you are doing, please don't use this script!!!
# 
# Prepend Header.h to all file in $1 directory matching *.$2
# Then change the svn property to replace Date Author Rev and HeadURL
# by their corresponding value.

for f in $(find $1 -name "*.$2"); do 
  cat Header.h $f > $f.tmp;
  mv $f.tmp $f;
  svn propset svn:keywords "Date Author Rev HeadURL" $f;
done;

